metrics:
  - reports/metrics.json

stages:

  download_data:
    cmd: uv run python3 src/stages/download_data.py --config=params.yaml
    params:
      - data
    deps:
      - src/stages/download_data.py
    outs:
      - data/digit-recognizer.zip

  unzip_data:
    cmd: uv run python3 src/stages/unzip_data.py --config=params.yaml
    params:
      - data
    deps:
      - src/stages/unzip_data.py
      - data/digit-recognizer.zip
    outs:
      - data/raw

  save_images:
    cmd: uv run python3 src/stages/save_images.py --config=params.yaml
    params:
      - data
    deps:
      - src/stages/save_images.py
      - data/raw
    outs:
      - data/saved

  split_data:
    cmd: uv run python3 src/stages/split_data.py --config=params.yaml
    params:
      - data
      - split
    deps:
      - src/stages/split_data.py
      - data/saved
    outs:
      - data/splits

  train:
    cmd: uv run python3 -m src.stages.train --config=params.yaml
    params:
      - train
    deps:
      - src/stages/train.py
      - src/transforms/train.py
      - data/splits
    outs:
      - models/weights.pt

  evaluate:
    cmd: uv run python3 -m src.stages.evaluate --config=params.yaml
    params:
      - evaluate
    deps:
      - src/stages/evaluate.py
      - src/transforms/test.py
      - data/splits
      - models/weights.pt
    outs:
      - reports/metrics.json

  predict:
    cmd: uv run python3 -m src.stages.predict --config=params.yaml
    params:
      - predict
    deps:
      - src/stages/predict.py
      - src/transforms/test.py
      - data/splits
      - models/weights.pt
    outs:
      - reports/submission.csv
